### PR TITLE
feat: picks target temperature from preset range if target temp is not set

### LINKED ISSUE #185: [Request] Set temperature value based on target_temp_* values when switching HVAC_Mode while Preset is set
When setting a preset while hvac_mode is not "heat_cool" while in "[DUAL Heat-Cool](https://github.com/swingerman/ha-dual-smart-thermostat?tab=readme-ov-file#dual-heat-cool-mode-example)" mode, if the temperature value is not defined, I think it would be good to select the temperature based on the mode,

if hvac_mode is cool, then set temperature to target_temp_low, if in heat set temperature to target_temp_high.

This will reduce/remove the need to update the config based on time of year.

### PR DESCRIPTION
**Pull request by swingerman**
Fixes #185

### CODE REVIEW

**Comment by T3chArmy** [comment]
@swingerman FYI I was testing the beta3 release and was getting occasional errors spit out.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/dual_smart_thermostat/managers/environment_manager.py:347
integration: dual_smart_thermostat (documentation, issues)
First occurred: 13:50:31 (3 occurrences)
Last logged: 13:54:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1078, in _async_control_climate
    await self.hvac_device.async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 84, in async_control_hvac
    await self._async_control_heat_cool(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 137, in _async_control_heat_cool
    await self.async_heater_cooler_toggle(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 147, in async_heater_cooler_toggle
    too_cold, too_hot, tolerance_device = self.is_cold_or_hot()
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 105, in is_cold_or_hot
    too_cold = self.environment.is_too_cold("_target_temp_low")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/managers/environment_manager.py", line 347, in is_too_cold
    return target_temp >= self._cur_temp + self._cold_tolerance
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

and

```
2024-06-02 12:33:52.944 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139721372687936] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 765, in async_handle_set_preset_mode_service
    await self.async_set_preset_mode(preset_mode)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1128, in async_set_preset_mode
    await self._async_control_climate(force=True)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1078, in _async_control_climate
    await self.hvac_device.async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 87, in async_control_hvac
    await super().async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/multi_hvac_device.py", line 148, in async_control_hvac
    await device.async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_device.py", line 81, in async_control_hvac
    await self._async_control_device_when_off(time)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_device.py", line 118, in _async_control_device_when_off
    too_cold = self.environment.is_too_cold(self.target_env_attr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/managers/environment_manager.py", line 347, in is_too_cold
    return target_temp >= self._cur_temp + self._cold_tolerance
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NodeDictClass' and 'float'
2024-06-02 12:34:05.610 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139721372687936] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 765, in async_handle_set_preset_mode_service
    await self.async_set_preset_mode(preset_mode)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1128, in async_set_preset_mode
    await self._async_control_climate(force=True)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1078, in _async_control_climate
    await self.hvac_device.async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 87, in async_control_hvac
    await super().async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/multi_hvac_device.py", line 148, in async_control_hvac
    await device.async_control_hvac(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_device.py", line 81, in async_control_hvac
    await self._async_control_device_when_off(time)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_device.py", line 118, in _async_control_device_when_off
    too_cold = self.environment.is_too_cold(self.target_env_attr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/managers/environment_manager.py", line 347, in is_too_cold
    return target_temp >= self._cur_temp + self._cold_tolerance
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NodeDictClass' and 'float'
```

**Comment by swingerman** [comment]
Thanks for sharing this. I am looking into it.

**Comment by 10der** [comment]
> Thanks for sharing this. I am looking into it.

btw

```
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 949, in _async_control_climate
    await self._async_control_cooling(time, force)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1133, in _async_control_cooling
    too_cold = self._is_too_cold()
               ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1470, in _is_too_cold
    return target_temp >= self._cur_temp + self._cold_tolerance
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

**Comment by swingerman** [comment]
@T3chArmy  I copied your configuration and was unable to reproduce the issue on my end.
Could you provide the exact sequence of actions that led to this error?

**Comment by T3chArmy** [comment]
I will attempt to reproduce this today. If I recall it had to do with switching the preset and then the mode or something like that. I will follow up in a few hours once I have some down time if I was able to reproduce.

**Pull request merged**
