### PR TITLE
fixing problem with support preset mode

### PR DESCRIPTION
**Pull request by alvarocarrera**
After updating set_hvac the _support_flags is properly updated. Moreover, the deprecated imports have been replaced with the new ClimateEntityFeature enum.

### CODE REVIEW

**Review by swingerman — APPROVED** [review]

**Review by swingerman — CHANGES_REQUESTED** [review]
Please make sure that tests are green

**Comment by alvarocarrera** [comment]
The problem was that the ClimateEntityFeature enum (available in core github repo: https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py ) is not available yet in the pytest-homeassistant-custom-component==0.8.7 module. Now all tests passed.

**Review by swingerman — APPROVED** [review]

**Comment by swingerman** [comment]
> The problem was that the ClimateEntityFeature enum (available in core github repo: https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py ) is not available yet in the pytest-homeassistant-custom-component==0.8.7 module. Now all tests passed.

Thanks mate!

**Comment by alvarocarrera** [comment]
> > The problem was that the ClimateEntityFeature enum (available in core github repo: https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py ) is not available yet in the pytest-homeassistant-custom-component==0.8.7 module. Now all tests passed.
> 
> Thanks mate!

You're welcome!

**Pull request merged**
